[tool.ruff]
# https://docs.astral.sh/ruff/configuration/
line-length = 120
output-format = "full"

[tool.ruff.lint]
ignore = [
    "E226", "E301", "E302", "E303", "E305", "E306", "E402",
    "E701", "E711", "E712", "E721", "E731", "E741",
]
